### ISSUE TITLE
Singular name, should be plural?

### ISSUE THREAD

**Issue by ConnectGrid** [square/square-php-sdk#112]
https://github.com/square/square-php-sdk/blob/f9d17fa069baf808f9cb3e42f56a5c13f1c4695d/src/Models/ListMerchantsResponse.php#L22

Maybe the reason for the `$merchant` properly being singular is that there is usually just a single entity, but in the interest of consistency, should it not be plural?

I discovered this when attempting to call `listMerchants()` when it is actually called `listMerchant()`, an illogical name.

Do you want pull-requests to correct issues like this, or can your team handle it?

**Comment by zenmasterjobo** [comment]
Hi @ConnectGrid,

Unfortunately this issue stems beyond the SDK itself and is defined at the [API level](https://developer.squareup.com/reference/square/merchants-api/list-merchants) - I definitely agree with you here that this is confusing, and because an access token can only have one merchant associated with it, the proper change here would be to make `Merchant` and singleton instead of an array.

I've opened this issue with the API team, but it's unlikely to get changed for some time coming. I will be closing this ticket though as it is not a fix we will make at the SDK level. When the API team updates the field it will propagate to the SDK.

Thank you very much for this feedback and helping us better our API interfaces!
