### ISSUE TITLE
Error: Class 'Square\SquareClient' not found

### ISSUE THREAD

**Issue by benlamptey** [square/square-php-sdk#83]
**Describe the bug**
For some reason, I get the following error: `Error: Class 'Square\SquareClient' not found` which is odd. I can definitely see the file.
Works on my local, but not on the server the site is hosted on.
Annoyingly, I have to transfer files the ancient way (FTP), so no composer. So I suspect composer might be needed on the server, but I genuinely have no idea. Would love some guidance if there's a manual way to install this properly.
(Also have in mind I am literally transferring everything composer would have downloaded to my local anyway)

**Expected behavior**

**Square SDK version**
I think its version 17. (Sadly upgrading from this isn't an option as the package I'm actually using relies on this particular version)

I toggled between php 7.4 and php 8 but no luck.
Forgive me if this has been reported and solved already. I couldn't find anything

If anyone is familiar with Drupal, I'm using the Commerce Square module - https://www.drupal.org/project/commerce_square/ that depends on the square sdk

**Comment by wolfadex** [comment]
@benlamptey the Commerce Square module is built and maintained by Square partner, if the issue is with their module then we recommend reaching out to them. You might also find some help on [our forums](https://developer.squareup.com/forums/) or [our Slack](https://buildwithsquare.slack.com/ssb/redirect). There you'll be likely to find more people who have experience building apps with the various SDKs. The GitHub issues is primarily for bugs and feature requests for the SDKs themselves.
