### ISSUE TITLE
Has error related to booking api

### ISSUE THREAD

**Issue by nha404** [square/square-php-sdk#98]
Describe the bug
Copied the example code (list booking) from docs and got the error.
Tried team-member-booking-profiles got same error.
Tried list-customers and it worked fine.

Expected behavior
Expect to see the list of booking

To Reproduce
Copy the php code from this https://developer.squareup.com/reference/square/bookings-api/list-bookings

Code detail:

```
   $api_response = $client->getBookingsApi()->listBookings();
    if ($api_response->isSuccess()) {
        $result = $api_response->getResult();
        var_dump($result);
    } else {
        $errors = $api_response->getErrors();
        var_dump("Error");
        var_dump($errors);
    }

```
Result
```
string(5) "Error"
array(1) {
  [0]=>
  object(Square\Models\Error)#39 (4) {
    ["category":"Square\Models\Error":private]=>
    string(8) "V1_ERROR"
    ["code":"Square\Models\Error":private]=>
    string(7) "Unknown"
    ["detail":"Square\Models\Error":private]=>
    NULL
    ["field":"Square\Models\Error":private]=>
    NULL
  }
}

```
Square SDK version
24.0.0.20221116

**Comment by jaypitpath** [comment]
Had same the issue got when I use the Retrieve Booking API but I checked and the issue is the content type. it's required application/json and returns text/plain so I took a fork and fixed this issue. the solution is to put the header in the parameter.

![image_2023_02_28T10_53_01_315Z](https://user-images.githubusercontent.com/121680381/221833709-7f2e2f34-761f-472f-9060-39e6804c5ad5.png)

**Comment by zenmasterjobo** [comment]
Hi @nha404 and @jaypitpath 

Apologies for the late reply here, but I have just checked our version `32.0.0.20231018` for this error, and it looks to be fixed. Please feel free to reach out / reopen if you continue to experience any further issues
